# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/dns_db
spring.datasource.username=user
spring.datasource.password=password
spring.sql.init.mode=always

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Автосоздание таблиц
spring.sql.init.mode=always
spring.web.resources.static-locations=classpath:/static/